# Generated by Django 5.2 on 2025-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_master_is_active_alter_master_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
