# Generated by Django 5.2 on 2025-05-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_notification_sent'),
        ('core', '0004_auto_20250529_1728'),
    ]

    operations = [
    ]
