# Generated by Django 5.2 on 2025-06-27 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('telegram_id', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Введите корректный Telegram ID (от 5 до 32 символов, буквы, цифры, знак подчеркивания)', regex='^@?[\\w]{5,32}$')], verbose_name='ID Telegram')),
                ('github_id', models.CharField(blank=True, max_length=39, validators=[django.core.validators.RegexValidator(message='Введите корректный GitHub ID (до 39 символов)', regex='^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$')], verbose_name='ID GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
