# Generated by Django 5.2 on 2025-06-27 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_github_id_profile_vk_id_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Введите корректный ID ВКонтакте (от 5 до 50 символов: буквы, цифры, точка, подчеркивание)', regex='^[a-zA-Z0-9_.]{5,50}$')], verbose_name='ID ВКонтакте'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
