# Generated by Django 5.2 on 2025-05-29 14:28

from django.db import migrations

def create_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    # Проверяем, существует ли уже объект Site с id=1
    if not Site.objects.filter(id=1).exists():
        Site.objects.create(
            id=1,
            domain='127.0.0.1:8000',
            name='localhost'
        )

class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_default_site),
    ]